import React from 'react';
import { 
  LayoutDashboard, 
  ShoppingBag, 
  ShoppingCart, 
  Wallet, 
  Package, 
  Heart, 
  BarChart3, 
  Settings,
  Search,
  User,
  Bell,
  ChevronRight,
  Plus,
  Trash2,
  MoreVertical,
  X,
  Check,
  Globe,
  DollarSign,
  Percent,
  ChefHat,
  Tag,
  Truck,
  Play,
  Shapes,
  Scale,
  Ruler,
  Menu,
  Building2,
  Store,
  CreditCard,
  Users,
  BookOpen,
  Cpu,
  Receipt,
  ArrowLeft,
  Circle,
  Square,
  Pentagon,
  Image as ImageIcon,
  Map,
  Maximize2,
  Warehouse,
  Printer,
  Smartphone
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Sales: ShoppingBag,
  Purchases: ShoppingCart,
  Finances: Wallet,
  Items: Package,
  Loyalty: Heart,
  Reports: BarChart3,
  Settings: Settings,
  Search: Search,
  User: User,
  Bell: Bell,
  ChevronRight: ChevronRight,
  Plus: Plus,
  Delete: Trash2,
  More: MoreVertical,
  Close: X,
  Check: Check,
  Language: Globe,
  Currency: DollarSign,
  Tax: Percent,
  Kitchen: ChefHat,
  Price: Tag,
  Delivery: Truck,
  Action: Play,
  Expense: Shapes,
  Weight: Scale,
  Ruler: Ruler,
  Menu: Menu,
  Company: Building2,
  Store: Store,
  Payment: CreditCard,
  UserManagement: Users,
  Dictionaries: BookOpen,
  Advanced: Cpu,
  Billing: Receipt,
  Back: ArrowLeft,
  Circle: Circle,
  Square: Square,
  Polygon: Pentagon,
  Image: ImageIcon,
  Map: Map,
  Table: Maximize2,
  Warehouse: Warehouse,
  Printer: Printer,
  Display: Smartphone
};